install.packages(file.path(datdir, "rasta_0.7.zip"), repos = NULL)
install.packages("RCurl", dependencies=TRUE)
library(RCurl)
download.file("http://rasta.r-forge.r-project.org/rasta.zip", file.path(datdir, "rasta_0.7.zip"))
install.packages('rasta', dependencies=TRUE)
library(rasta)
library(raster)
#library(rgdal)
#library(sp)
#library(ggplot2)
#library(rasterVis)
#library(zoo)
#library(reshape)
update.packages(checkBuilt = TRUE, ask = FALSE)