install.packages("RCurl", dependencies=TRUE)
library(RCurl)
library(rgdal)
library(sp)
library(ggplot2)
install.packages("digest")
library(digest)
library(rgeos)
update.packages(checkBuilt = TRUE, ask = FALSE)